private_api_ci: &private_api_ci
  - '.github/workflows/private-api.*.yml'

private_api:
  - *private_api_ci
  - 'apps/private-api/**'

public_api_ci: &public_api_ci
  - '.github/workflows/public-api.*.yml'

public_api:
  - *public_api_ci
  - 'apps/public-api/**'

web_ci: &web_ci
  - '.github/workflows/web.*.yml'

web:
  - *web_ci
  - 'apps/web/**'
