version: '3'

services:
  db:
    image: postgres:17.2
    container_name: chat_connect_db
    ports:
      - 15432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db-store:
