steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - .
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/chat-connect/chat-connect-web:${_COMMIT_SHA}
  - -f
  - ./apps/web/Dockerfile
  automapSubstitutions: true
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-connect/chat-connect-web:${_COMMIT_SHA}']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'chat-connect-web'
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-connect/chat-connect-web:${_COMMIT_SHA}'
  - '--region'
  - 'us-central1'
  - ' --service-account'
  - '${_SERVICE_ACCOUNT}'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/chat-connect/chat-connect-web:${_COMMIT_SHA}'
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/${_SERVICE_ACCOUNT}'
options:
  logging: 'CLOUD_LOGGING_ONLY'
