name: Deploy
on: 
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Repository check
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'chat-connect-production'
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'write diff dir'
        run: |
          git fetch --depth=2 origin main
          git log
          git --no-pager diff --name-only HEAD^ HEAD | grep "apps/" | cut -d/ -f2 | sort | uniq > ./diff.txt

      - name: 'gcloud builds submit'
        run: |
          while read line
          do 
          config="./${line}.cloudbuild.yaml"
          echo $config
          if [[ ! -f "${config}" ]]; then
            echo "no such file"
            continue
          fi
          gcloud builds submit --config=${config} --substitutions=_COMMIT_SHA=${{ github.sha }} --service-account=${{ secrets.GCP_SERVICE_ACCOUNT }} .
          echo ${line}
          done < ./diff.txt
