name: Web Deploy
on: 
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'chat-connect-production'
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: 'Build and push container'
        run: |-
          docker build -t "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chat-connect/chat-connect-web:${{ github.sha }}" . -f ./apps/web/Dockerfile
          docker push "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/chat-connect/chat-connect-web:${{ github.sha }}"

      - name: 'Deploy to Cloud Run'
        run: |-
          gcloud run deploy chat-connect-web --image us-central1-docker.pkg.dev/$PROJECT_ID/chat-connect/chat-connect-web:${{ github.sha }} --region us-central1'
